# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nikitos\PycharmProjects\TMTB_GUI\change_passwrod.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class change_passwrod(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 200)
        Form.setMinimumSize(QtCore.QSize(300, 200))
        Form.setMaximumSize(QtCore.QSize(300, 200))
        Form.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0 ; \n"
"    margin:0;\n"
"    color:#fff;\n"
"}\n"
"#Central_widget{\n"
"    background-color:rgb(42, 54, 63);\n"
"    \n"
"}\n"
"#widget{\n"
"\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"padding: 5px 3px;\n"
"border-radius: 5px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton{\n"
"\n"
"padding: 10px 5px;\n"
"\n"
"opacity: 1;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"background-color: rgb(144, 206, 161);\n"
"color:white;\n"
"}      \n"
"\n"
"")
        self.Central_widget = QtWidgets.QWidget(Form)
        self.Central_widget.setGeometry(QtCore.QRect(0, 0, 300, 200))
        self.Central_widget.setMinimumSize(QtCore.QSize(300, 200))
        self.Central_widget.setMaximumSize(QtCore.QSize(300, 200))
        self.Central_widget.setObjectName("Central_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Central_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.Central_widget)
        self.widget.setMinimumSize(QtCore.QSize(200, 200))
        self.widget.setMaximumSize(QtCore.QSize(200, 200))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem)
        self.New_password = QtWidgets.QLineEdit(self.widget)
        self.New_password.setObjectName("New_password")
        self.New_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayout_5.addWidget(self.New_password)
        self.wrong_password = QtWidgets.QLabel(self.widget)
        self.wrong_password.setEnabled(True)
        self.wrong_password.setMinimumSize(QtCore.QSize(0, 13))
        self.wrong_password.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.wrong_password.setFont(font)
        self.wrong_password.setStyleSheet("color:red;\n"
"")
        self.wrong_password.setLineWidth(1)
        self.wrong_password.setMidLineWidth(13)
        self.wrong_password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.wrong_password.setObjectName("wrong_password")
        self.verticalLayout_5.addWidget(self.wrong_password)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem1)
        self.Confirm_password = QtWidgets.QPushButton(self.widget)
        self.Confirm_password.setObjectName("Confirm_password")
        self.verticalLayout_5.addWidget(self.Confirm_password)
        spacerItem2 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.New_password.setPlaceholderText(_translate("Form", "New password"))
        self.wrong_password.setText(_translate("Form", "Wrong email"))
        self.Confirm_password.setText(_translate("Form", "Confirm"))
import res
