# Form implementation generated from reading ui file 'D:\fogort_GUI.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Fogort_page(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 500)
        Form.setMinimumSize(QtCore.QSize(300, 500))
        Form.setMaximumSize(QtCore.QSize(300, 500))
        Form.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0 ; \n"
"    margin:0;\n"
"    color:#fff;\n"
"}\n"
"#Central_widget{\n"
"    background-color:rgb(42, 54, 63);\n"
"    \n"
"}\n"
"#widget{\n"
"\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"padding: 5px 3px;\n"
"border-radius: 5px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton{\n"
"\n"
"padding: 10px 5px;\n"
"\n"
"opacity: 1;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"background-color: rgb(144, 206, 161);\n"
"color:white;\n"
"}      \n"
"\n"
"")
        self.Central_widget = QtWidgets.QWidget(Form)
        self.Central_widget.setGeometry(QtCore.QRect(0, 0, 300, 500))
        self.Central_widget.setMinimumSize(QtCore.QSize(300, 500))
        self.Central_widget.setMaximumSize(QtCore.QSize(300, 500))
        self.Central_widget.setObjectName("Central_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Central_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.Central_widget)
        self.widget.setMinimumSize(QtCore.QSize(200, 400))
        self.widget.setMaximumSize(QtCore.QSize(200, 400))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(35, 35))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/door-key-access-svgrepo-com.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_5.addItem(spacerItem)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.emai_warn_label = QtWidgets.QLabel(self.widget)
        self.emai_warn_label.setEnabled(True)
        self.emai_warn_label.setMinimumSize(QtCore.QSize(0, 13))
        self.emai_warn_label.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.emai_warn_label.setFont(font)
        self.emai_warn_label.setStyleSheet("color:red;\n"
"")
        self.emai_warn_label.setLineWidth(1)
        self.emai_warn_label.setMidLineWidth(13)
        self.emai_warn_label.setText("")
        self.emai_warn_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.emai_warn_label.setObjectName("emai_warn_label")
        self.verticalLayout_5.addWidget(self.emai_warn_label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_5.addItem(spacerItem1)
        self.sent_mail_button = QtWidgets.QPushButton(self.widget)
        self.sent_mail_button.setObjectName("sent_mail_button")
        self.verticalLayout_5.addWidget(self.sent_mail_button)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_5.addItem(spacerItem2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_5.addWidget(self.lineEdit_2)
        self.code_warn_label = QtWidgets.QLabel(self.widget)
        self.code_warn_label.setEnabled(True)
        self.code_warn_label.setMinimumSize(QtCore.QSize(0, 13))
        self.code_warn_label.setMaximumSize(QtCore.QSize(16777215, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.code_warn_label.setFont(font)
        self.code_warn_label.setStyleSheet("color:red;\n"
"")
        self.code_warn_label.setLineWidth(1)
        self.code_warn_label.setMidLineWidth(13)
        self.code_warn_label.setText("")
        self.code_warn_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.code_warn_label.setObjectName("code_warn_label")
        self.verticalLayout_5.addWidget(self.code_warn_label)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_5.addItem(spacerItem3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_5.addWidget(self.lineEdit_3)
        self.newpass_warn_label = QtWidgets.QLabel(self.widget)
        self.newpass_warn_label.setEnabled(True)
        self.newpass_warn_label.setMinimumSize(QtCore.QSize(0, 13))
        self.newpass_warn_label.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.newpass_warn_label.setFont(font)
        self.newpass_warn_label.setStyleSheet("color:red;\n"
"")
        self.newpass_warn_label.setLineWidth(1)
        self.newpass_warn_label.setMidLineWidth(13)
        self.newpass_warn_label.setText("")
        self.newpass_warn_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.newpass_warn_label.setObjectName("newpass_warn_label")
        self.verticalLayout_5.addWidget(self.newpass_warn_label)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_5.addItem(spacerItem4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_5.addWidget(self.lineEdit_4)
        self.confirmpass_warn_label = QtWidgets.QLabel(self.widget)
        self.confirmpass_warn_label.setEnabled(True)
        self.confirmpass_warn_label.setMinimumSize(QtCore.QSize(0, 13))
        self.confirmpass_warn_label.setMaximumSize(QtCore.QSize(16777215, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.confirmpass_warn_label.setFont(font)
        self.confirmpass_warn_label.setStyleSheet("color:red;\n"
"")
        self.confirmpass_warn_label.setLineWidth(1)
        self.confirmpass_warn_label.setMidLineWidth(13)
        self.confirmpass_warn_label.setText("")
        self.confirmpass_warn_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.confirmpass_warn_label.setObjectName("confirmpass_warn_label")
        self.verticalLayout_5.addWidget(self.confirmpass_warn_label)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        self.verticalLayout_5.addItem(spacerItem5)
        self.change_pass_button = QtWidgets.QPushButton(self.widget)
        self.change_pass_button.setObjectName("change_pass_button")
        self.verticalLayout_5.addWidget(self.change_pass_button)
        self.verticalLayout_4.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Email"))
        self.sent_mail_button.setText(_translate("Form", "Sent"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Code"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "New Password"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Confirm Password"))
        self.change_pass_button.setText(_translate("Form", "Sent"))



