# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fogort_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
from forgotPassword import *

class Forgot_page(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 500)
        Form.setMinimumSize(QtCore.QSize(300, 500))
        Form.setMaximumSize(QtCore.QSize(300, 500))
        Form.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0 ; \n"
"    margin:0;\n"
"    color:#fff;\n"
"}\n"
"#Central_widget{\n"
"    background-color:rgb(42, 54, 63);\n"
"    \n"
"}\n"
"#widget{\n"
"\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"padding: 5px 3px;\n"
"border-radius: 5px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton{\n"
"\n"
"padding: 10px 5px;\n"
"\n"
"opacity: 1;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"background-color: rgb(144, 206, 161);\n"
"color:white;\n"
"}      \n"
"\n"
"")
        self.Central_widget = QtWidgets.QWidget(Form)
        self.Central_widget.setGeometry(QtCore.QRect(0, 0, 300, 500))
        self.Central_widget.setMinimumSize(QtCore.QSize(300, 500))
        self.Central_widget.setMaximumSize(QtCore.QSize(300, 500))
        self.Central_widget.setObjectName("Central_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Central_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.Central_widget)
        self.widget.setMinimumSize(QtCore.QSize(200, 300))
        self.widget.setMaximumSize(QtCore.QSize(200, 300))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(35, 35))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/door-key-access-svgrepo-com.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem)
        self.Email_forgot_password = QtWidgets.QLineEdit(self.widget)
        self.Email_forgot_password.setObjectName("Email_forgot_password")
        self.verticalLayout_5.addWidget(self.Email_forgot_password)
        self.wrong_email = QtWidgets.QLabel(self.widget)
        self.wrong_email.setEnabled(True)
        self.wrong_email.setMinimumSize(QtCore.QSize(0, 13))
        self.wrong_email.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.wrong_email.setFont(font)
        self.wrong_email.setStyleSheet("color:red;\n"
"")
        self.wrong_email.setLineWidth(1)
        self.wrong_email.setMidLineWidth(13)
        self.wrong_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.wrong_email.setObjectName("wrong_email")
        self.verticalLayout_5.addWidget(self.wrong_email)
        self.sentCodelForgotBttn = QtWidgets.QPushButton(self.widget)
        self.sentCodelForgotBttn.setObjectName("sentCodelForgotBttn")
        self.verticalLayout_5.addWidget(self.sentCodelForgotBttn)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 13))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.Code_forgot_password = QtWidgets.QLineEdit(self.widget)
        self.Code_forgot_password.setEnabled(True)
        self.Code_forgot_password.setObjectName("Code_forgot_password")
        self.verticalLayout_5.addWidget(self.Code_forgot_password)
        self.wrong_code = QtWidgets.QLabel(self.widget)
        self.wrong_code.setEnabled(True)
        self.wrong_code.setMinimumSize(QtCore.QSize(0, 13))
        self.wrong_code.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.wrong_code.setFont(font)
        self.wrong_code.setStyleSheet("color:red;\n"
"")
        self.wrong_code.setLineWidth(1)
        self.wrong_code.setMidLineWidth(13)
        self.wrong_code.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.wrong_code.setObjectName("wrong_code")
        self.verticalLayout_5.addWidget(self.wrong_code)
        self.New_password = QtWidgets.QLineEdit(self.widget)
        self.New_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.New_password.setObjectName("New_password")
        self.verticalLayout_5.addWidget(self.New_password)
        self.wrong_password = QtWidgets.QLabel(self.widget)
        self.wrong_password.setEnabled(True)
        self.wrong_password.setMinimumSize(QtCore.QSize(0, 13))
        self.wrong_password.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.wrong_password.setFont(font)
        self.wrong_password.setStyleSheet("color:red;\n"
"")
        self.wrong_password.setLineWidth(1)
        self.wrong_password.setMidLineWidth(13)
        self.wrong_password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.wrong_password.setObjectName("wrong_password")
        self.verticalLayout_5.addWidget(self.wrong_password)
        self.Confirm_password_forgot_page = QtWidgets.QLineEdit(self.widget)
        self.Confirm_password_forgot_page.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Confirm_password_forgot_page.setObjectName("Confirm_password_forgot_page")
        self.verticalLayout_5.addWidget(self.Confirm_password_forgot_page)
        self.wrongPassword2 = QtWidgets.QLabel(self.widget)
        self.wrongPassword2.setMinimumSize(QtCore.QSize(0, 13))
        self.wrongPassword2.setMaximumSize(QtCore.QSize(0, 0))
        self.wrongPassword2.setStyleSheet("color: rgb(255, 0, 0);")
        self.wrongPassword2.setObjectName("wrongPassword2")
        self.verticalLayout_5.addWidget(self.wrongPassword2)
        self.acceptNewPassBttn = QtWidgets.QPushButton(self.widget)
        self.acceptNewPassBttn.setObjectName("acceptNewPassBttn")
        self.verticalLayout_5.addWidget(self.acceptNewPassBttn)
        self.verticalLayout_4.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)

        QtCore.QMetaObject.connectSlotsByName(Form)
        self.sentCodelForgotBttn.clicked.connect(self.sentCode)
        self.acceptNewPassBttn.clicked.connect(self.NewPass)
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Email_forgot_password.setPlaceholderText(_translate("Form", "Email"))
        self.wrong_email.setText(_translate("Form", "Wrong email"))
        self.sentCodelForgotBttn.setText(_translate("Form", "Sent"))
        self.Code_forgot_password.setPlaceholderText(_translate("Form", "Code"))
        self.wrong_code.setText(_translate("Form", "Wrong code"))
        self.New_password.setPlaceholderText(_translate("Form", "New Password"))
        self.wrong_password.setText(_translate("Form", "The new password does not fit"))
        self.Confirm_password_forgot_page.setPlaceholderText(_translate("Form", "Confirm Password"))
        self.wrongPassword2.setText(_translate("Form", "The passwords don\'t match"))
        self.acceptNewPassBttn.setText(_translate("Form", "Accept new password"))

    def sentCode(self):
        sent(self.Email_forgot_password,self.wrong_email)
    def NewPass(self):
        newpassword(self.Code_forgot_password,self.New_password,self.Confirm_password_forgot_page,self.Email_forgot_password,self.wrong_email,self.wrong_password,self.wrong_code,self.wrongPassword2)