# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nikitos\PycharmProjects\TMTB_GUI\fogort_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Forgot_page(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 500)
        Form.setMinimumSize(QtCore.QSize(300, 500))
        Form.setMaximumSize(QtCore.QSize(300, 500))
        Form.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0 ; \n"
"    margin:0;\n"
"    color:#fff;\n"
"}\n"
"#Central_widget{\n"
"    background-color:rgb(42, 54, 63);\n"
"    \n"
"}\n"
"#widget{\n"
"\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"\n"
"padding: 5px 3px;\n"
"border-radius: 5px;\n"
"border: 1px solid gray;\n"
"}\n"
"\n"
"QPushButton{\n"
"\n"
"padding: 10px 5px;\n"
"\n"
"opacity: 1;\n"
"border-radius: 5px;\n"
"\n"
"\n"
"background-color: rgb(144, 206, 161);\n"
"color:white;\n"
"}      \n"
"\n"
"")
        self.Central_widget = QtWidgets.QWidget(Form)
        self.Central_widget.setGeometry(QtCore.QRect(0, 0, 300, 500))
        self.Central_widget.setMinimumSize(QtCore.QSize(300, 500))
        self.Central_widget.setMaximumSize(QtCore.QSize(300, 500))
        self.Central_widget.setObjectName("Central_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Central_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget = QtWidgets.QWidget(self.Central_widget)
        self.widget.setMinimumSize(QtCore.QSize(200, 300))
        self.widget.setMaximumSize(QtCore.QSize(200, 300))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMaximumSize(QtCore.QSize(35, 35))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/door-key-access-svgrepo-com.svg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem)
        self.Email_forgot_password = QtWidgets.QLineEdit(self.widget)
        self.Email_forgot_password.setObjectName("Email_forgot_password")
        self.verticalLayout_5.addWidget(self.Email_forgot_password)
        self.wrong_email = QtWidgets.QLabel(self.widget)
        self.wrong_email.setEnabled(True)
        self.wrong_email.setMinimumSize(QtCore.QSize(0, 13))
        self.wrong_email.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.wrong_email.setFont(font)
        self.wrong_email.setStyleSheet("color:red;\n"
"")
        self.wrong_email.setLineWidth(1)
        self.wrong_email.setMidLineWidth(13)
        self.wrong_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.wrong_email.setObjectName("wrong_email")
        self.verticalLayout_5.addWidget(self.wrong_email)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem1)
        self.sent_forgot_page = QtWidgets.QPushButton(self.widget)
        self.sent_forgot_page.setObjectName("sent_forgot_page")
        self.verticalLayout_5.addWidget(self.sent_forgot_page)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem2)
        self.Code_forgot_password = QtWidgets.QLineEdit(self.widget)
        self.Code_forgot_password.setEnabled(True)
        self.Code_forgot_password.setObjectName("Code_forgot_password")
        self.verticalLayout_5.addWidget(self.Code_forgot_password)
        self.wrong_code = QtWidgets.QLabel(self.widget)
        self.wrong_code.setEnabled(True)
        self.wrong_code.setMinimumSize(QtCore.QSize(0, 13))
        self.wrong_code.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wrong_code.setFont(font)
        self.wrong_code.setStyleSheet("color:red;\n"
"")
        self.wrong_code.setLineWidth(1)
        self.wrong_code.setMidLineWidth(13)
        self.wrong_code.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.wrong_code.setObjectName("wrong_code")
        self.verticalLayout_5.addWidget(self.wrong_code)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem3)
        self.New_password = QtWidgets.QLineEdit(self.widget)
        self.New_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.New_password.setObjectName("New_password")
        self.verticalLayout_5.addWidget(self.New_password)
        self.wrong_password = QtWidgets.QLabel(self.widget)
        self.wrong_password.setEnabled(True)
        self.wrong_password.setMinimumSize(QtCore.QSize(0, 13))
        self.wrong_password.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.wrong_password.setFont(font)
        self.wrong_password.setStyleSheet("color:red;\n"
"")
        self.wrong_password.setLineWidth(1)
        self.wrong_password.setMidLineWidth(13)
        self.wrong_password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.wrong_password.setObjectName("wrong_password")
        self.verticalLayout_5.addWidget(self.wrong_password)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem4)
        self.Confirm_password_forgot_page = QtWidgets.QLineEdit(self.widget)
        self.Confirm_password_forgot_page.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Confirm_password_forgot_page.setObjectName("Confirm_password_forgot_page")
        self.verticalLayout_5.addWidget(self.Confirm_password_forgot_page)
        self.confirm_password_error = QtWidgets.QLabel(self.widget)
        self.confirm_password_error.setEnabled(True)
        self.confirm_password_error.setMinimumSize(QtCore.QSize(0, 13))
        self.confirm_password_error.setMaximumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.confirm_password_error.setFont(font)
        self.confirm_password_error.setStyleSheet("color:red;\n"
"")
        self.confirm_password_error.setLineWidth(1)
        self.confirm_password_error.setMidLineWidth(13)
        self.confirm_password_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.confirm_password_error.setObjectName("confirm_password_error")
        self.verticalLayout_5.addWidget(self.confirm_password_error)
        self.verticalLayout_4.addWidget(self.widget, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Email_forgot_password.setPlaceholderText(_translate("Form", "Email"))
        self.wrong_email.setText(_translate("Form", "Wrong email"))
        self.sent_forgot_page.setText(_translate("Form", "Sent"))
        self.Code_forgot_password.setPlaceholderText(_translate("Form", "Code"))
        self.wrong_code.setText(_translate("Form", "Wrong code"))
        self.New_password.setPlaceholderText(_translate("Form", "New Password"))
        self.wrong_password.setText(_translate("Form", "nie podchody po pravilam"))
        self.Confirm_password_forgot_page.setPlaceholderText(_translate("Form", "Confirm Password"))
        self.confirm_password_error.setText(_translate("Form", "nie podchody po pravilam"))
import res
