# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nikitos\PycharmProjects\TMTB_GUI\main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Main_page(object):
    def setupUi(self, Form):

        Form.setObjectName("Form")
        Form.resize(1000, 600)
        Form.setMinimumSize(QtCore.QSize(1000, 600))
        Form.setMaximumSize(QtCore.QSize(1000, 600))
        Form.setStyleSheet("*{\n"
"    \n"
"    background-color: transparent;\n"
"    background: transparent;\n"
"    padding: 0 ; \n"
"    margin:0;\n"
"\n"
"}\n"
"#menu_bttn{\n"
"    \n"
"    background-color: rgb(110, 217, 160);\n"
"}\n"
"#account_buttn{\n"
"    \n"
"    background-color: rgb(110, 217, 160);\n"
"}\n"
"\n"
"\n"
"#Central_widget{\n"
"    background-color:rgb(42, 54, 63);\n"
"color:black;\n"
"}\n"
"#widget{\n"
"background-color: #9C9EFE;\n"
"border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"\n"
"QLineEdit{\n"
"background-color:#FAF3F3;\n"
"padding: 5px 3px;\n"
"border-radius: 5px;\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton{\n"
"\n"
"padding: 10px 5px;\n"
"\n"
"\n"
"background-color:#6ED9A0;\n"
"border-radius:5 px;\n"
"border-color: rgb(0, 0, 0);\n"
"opacity: 1;\n"
"\n"
"}      \n"
"\n"
"")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1000, 600))
        self.widget.setMinimumSize(QtCore.QSize(1000, 600))
        self.widget.setMaximumSize(QtCore.QSize(1000, 600))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_menu = QtWidgets.QWidget(self.widget)
        self.top_menu.setMinimumSize(QtCore.QSize(1000, 50))
        self.top_menu.setMaximumSize(QtCore.QSize(1000, 50))
        self.top_menu.setStyleSheet("background-color:pink;")
        self.top_menu.setObjectName("top_menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_menu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.menu = QtWidgets.QWidget(self.top_menu)
        self.menu.setMinimumSize(QtCore.QSize(50, 50))
        self.menu.setMaximumSize(QtCore.QSize(50, 50))
        self.menu.setStyleSheet("QWidget\n"
"{\n"
"background-color:#6ED9A0;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color:#9BA7A5;\n"
"}\n"
"\n"
"")
        self.menu.setObjectName("menu")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.menu)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.menu_buttn = QtWidgets.QPushButton(self.menu)
        self.menu_buttn.setMinimumSize(QtCore.QSize(40, 40))
        self.menu_buttn.setMaximumSize(QtCore.QSize(50, 50))
        self.menu_buttn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_buttn.setIcon(icon)
        self.menu_buttn.setIconSize(QtCore.QSize(25, 25))
        self.menu_buttn.setObjectName("menu_buttn")
        self.horizontalLayout_5.addWidget(self.menu_buttn)
        self.horizontalLayout.addWidget(self.menu)
        self.widget_2 = QtWidgets.QWidget(self.top_menu)
        self.widget_2.setMaximumSize(QtCore.QSize(900, 16777215))
        self.widget_2.setStyleSheet("background-color: rgb(42, 54, 63);")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setMinimumSize(QtCore.QSize(50, 50))
        self.widget_4.setMaximumSize(QtCore.QSize(50, 50))
        self.widget_4.setStyleSheet("background-color: rgb(42, 54, 63);")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/2560px-Tmdb.new.logo.svg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMinimumSize(QtCore.QSize(870, 50))
        self.widget_3.setMaximumSize(QtCore.QSize(870, 50))
        self.widget_3.setStyleSheet("background-color: rgb(42, 54, 63);")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.widget_3)
        self.widget_5.setMinimumSize(QtCore.QSize(340, 41))
        self.widget_5.setMaximumSize(QtCore.QSize(340, 40))
        self.widget_5.setStyleSheet("#widget_5\n"
"{\n"
"border-radius:10px;\n"
"border:2px solid #696d6d;\n"
"}\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setContentsMargins(-1, 7, -1, 6)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget_5)
        self.label_2.setMinimumSize(QtCore.QSize(24, 24))
        self.label_2.setMaximumSize(QtCore.QSize(24, 24))
        self.label_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icon/search-svgrepo-com.svg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.search = QtWidgets.QLineEdit(self.widget_5)
        self.search.setMinimumSize(QtCore.QSize(0, 30))
        self.search.setMaximumSize(QtCore.QSize(300, 100))
        self.search.setSizeIncrement(QtCore.QSize(0, 0))
        self.search.setStyleSheet("\n"
"background:transparent;;\n"
"font: 18pt \"MS Shell Dlg 2\";\n"
"\n"
"color:#bfc5c5;")
        self.search.setObjectName("search")
        self.horizontalLayout_4.addWidget(self.search)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(24, 24))
        self.pushButton_6.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_6.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/arrow-down.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget_2)
        self.user_icon = QtWidgets.QFrame(self.top_menu)
        self.user_icon.setMinimumSize(QtCore.QSize(130, 50))
        self.user_icon.setMaximumSize(QtCore.QSize(50, 50))
        self.user_icon.setStyleSheet("background-color: rgb(42, 54, 63);")
        self.user_icon.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_icon.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_icon.setObjectName("user_icon")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.user_icon)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.frame_3 = QtWidgets.QFrame(self.user_icon)
        self.frame_3.setMinimumSize(QtCore.QSize(30, 49))
        self.frame_3.setMaximumSize(QtCore.QSize(50, 50))
        self.frame_3.setStyleSheet("color:#bfc5c5;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 16)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_4.addWidget(self.label_10)
        self.horizontalLayout_8.addWidget(self.frame_3)
        self.label_8 = QtWidgets.QLabel(self.user_icon)
        self.label_8.setMaximumSize(QtCore.QSize(35, 35))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/icon/1613328317_108-p-kislotno-sinii-fon-148.jpg"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.horizontalLayout.addWidget(self.user_icon)
        self.verticalLayout.addWidget(self.top_menu)
        self.body = QtWidgets.QWidget(self.widget)
        self.body.setMinimumSize(QtCore.QSize(0, 50))
        self.body.setStyleSheet("background-color:rgb(42, 54, 63);")
        self.body.setObjectName("body")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.body)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.left_menu = QtWidgets.QFrame(self.body)
        self.left_menu.setMinimumSize(QtCore.QSize(0, 550))
        self.left_menu.setMaximumSize(QtCore.QSize(50, 550))
        self.left_menu.setStyleSheet("QFrame\n"
"{\n"
"background-color:#6ED9A0;\n"
"}\n"
"QPushButton{\n"
"    padding: 5px 10px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color:#6ED9A0;\n"
"    color:#F6F8F7;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"background-color:#9BA7A5;\n"
"}\n"
"")
        self.left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu.setObjectName("left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.left_menu)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setContentsMargins(10, 15, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(156, 31))
        self.pushButton.setMaximumSize(QtCore.QSize(156, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-image: url(:/icon/home.svg);\n"
"background-repeat:none;\n"
"background-position:center left;\n"
"padding-left:30px;\n"
"")
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(156, 31))
        self.pushButton_2.setMaximumSize(QtCore.QSize(156, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-image: url(:/icon/heart.svg);\n"
"background-repeat:none;\n"
"background-position:center left;\n"
"padding-left:30px;\n"
"")
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(156, 31))
        self.pushButton_3.setMaximumSize(QtCore.QSize(156, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-image: url(:/icon/pause.svg);\n"
"background-repeat:none;\n"
"background-position:center left;\n"
"padding-left:30px;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(156, 31))
        self.pushButton_4.setMaximumSize(QtCore.QSize(156, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-image: url(:/icon/history-svgrepo-com.svg);\n"
"background-repeat:none;\n"
"background-position:center left;\n"
"padding-left:30px;\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.pushButton_4)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(20, 380))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.frame_2)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(156, 31))
        self.pushButton_5.setMaximumSize(QtCore.QSize(156, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("background-image: url(:/icon/settings.svg);\n"
"background-repeat:none;\n"
"background-position:center left;\n"
"padding-left:30px;\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.pushButton_5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(4, QtWidgets.QFormLayout.LabelRole, spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(8, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(12, QtWidgets.QFormLayout.LabelRole, spacerItem4)
        self.verticalLayout_3.addWidget(self.frame)
        self.horizontalLayout_6.addWidget(self.left_menu)
        self.main_body = QtWidgets.QFrame(self.body)
        self.main_body.setStyleSheet("background-color: rgb(42, 54, 63);")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_body)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_7.addWidget(self.stackedWidget)
        self.horizontalLayout_6.addWidget(self.main_body)
        self.verticalLayout.addWidget(self.body)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.search.setPlaceholderText(_translate("Form", "Search"))
        self.label_9.setText(_translate("Form", "Username"))
        self.label_10.setText(_translate("Form", "Id: 23232"))
        self.pushButton.setText(_translate("Form", "Home"))
        self.pushButton_2.setText(_translate("Form", "Favorite"))
        self.pushButton_3.setText(_translate("Form", "Later"))
        self.pushButton_4.setText(_translate("Form", "History"))
        self.pushButton_5.setText(_translate("Form", "Settings"))
import res